databases:
  - name: geeeeg_DB
    databaseName: geeeeg_db
    user: geeeeg
    region: singapore

services:
  - type: web
    name: geeeeg
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: geeeeg_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

